src/Routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::prefix('/panel')->middleware('auth')->group( function () {
    Route::resource('pages' , 'PageController');
    Route::get('pages/{id}/subpages','PageController@subPages')->name('subpages');
    Route::post('pages/checkurl','PageController@urlControl')->name('pages.checkurl');
    Route::resource('files' , 'FileController');
    Route::post('files/ajax','FileController@ajax')->name('file.ajax');
    Route::resource('languages' , 'LanguageController');
    Route::resource('categories','CategoryController');
    Route::post('category/order','CategoryController@order')->name('categories.order');

    Route::resource('metas' , 'MetaController');
    Route::resource('redirects' , 'RedirectController');

    //Form-Ebulletin
    Route::resource('forms','FormController');
    Route::resource('forms.messages','MessageController');
    Route::resource('messages','MessageController')->only(['show','store']);
    Route::resource('ebulletins' , 'EbulletinController');

    //Auth
    Route::resource('users' , 'UserController');
    Route::resource('roles' , 'RoleController');

    Route::get('/','HomeController@index')->name('panel');

    Route::get('login',function (){ return view('auth/login');})->name('login');

    Route::get('getFilePage','FileController@getFilePage')->name('files.getFilePage');
    Route::get('getFilePageDetail','FileController@getFilePageDetail')->name('files.getFilePageDetail');

    Route::post('saveFilePage','FileController@saveFilePage')->name('files.saveFilePage');
    Route::post('saveFilePageDetail','FileController@saveFilePageDetail')->name('files.saveFilePageDetail');

    Route::post('uploadFile','FileController@uploadFile')->name('files.uploadFile');

    Route::get('googleAnalytics','AnalyticsController@google')->name('analytics.google');

    Route::resource('slider','SliderController');
    Route::post('slider/add-image','SliderController@addImage')->name('addImage');
    Route::post('slider/delete-image','SliderController@deleteImage')->name('delimage');
    Route::post('slider/get-slider-image','SliderController@getSliderImage')->name('getSliderImage');
    Route::post('slider/edit-image','SliderController@editImage')->name('editImage');
    //Menu
    Route::resource('menu', 'MenuController');
    Route::post('menu/ajax','MenuController@ajax')->name('menuajax');
    Route::get('menu/item/{menuitem}/delete','MenuController@destroyMenuItem')->name('delete-item');
    Route::post('menuitem/ajax/','MenuController@storeMenuItem')->name('menuitemajax');

});

Route::get('panel/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('panel/login/', 'Auth\LoginController@login');
Route::post('panel/logout', 'Auth\LoginController@logout')->name('logout');


Route::group(['prefix'=>'ebulletin'],function(){
    Route::get('activate/{token}', 'EbulletinController@activate')->name('ebulletin-activate');
    Route::get('cancel/{token}', 'EbulletinController@cancel')->name('ebulletin-cancel');
    Route::post('store','EbulletinController@store')->name('ebulletin-store');
});


Route::post('form/store','MessageController@store')->name('form');
Route::fallback('UrlController@url');

Route::get('/home', 'HomeController@index')->name('home');
Route::any('/ckfinder/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')
    ->name('ckfinder_connector');

Route::any('/ckfinder/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')
    ->name('ckfinder_browser');

src/Models/Redirect.php
<?php

namespace CMS\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Redirect extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'from', 'to', 'code', 'status'
    ];
}

src/Resources/views/panel/redirect/create.blade.php
@extends('cms::panel.inc.app')
@push('css')

@endpush

@push('js')
@endpush
@section('content')
    <div class="page-wrapper">
        <div class="container-fluid">
            @include('cms::panel.inc.breadcrumb')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-block">
                            <form method="POST" action="{!! route('redirects.store') !!}">
                                @method('POST')
                                @csrf
                                <div class="form-group">
                                    <label>{!! trans('cms::redirect.from') !!}</label>
                                    <input type="text" class="form-control" id="from" name="from" placeholder="{!! trans('cms::redirect.from') !!}" value="{!! old('from') !!}">
                                    @include('cms::panel.inc.form_error',['input_name' => 'from'])
                                </div>
                                <div class="form-group">
                                    <label>{!! trans('cms::redirect.to') !!}</label>
                                    <input type="text" class="form-control" id="to" name="to" placeholder="{!! trans('cms::redirect.to') !!}" value="{!! old('to') !!}">
                                    @include('cms::panel.inc.form_error',['input_name' => 'to'])
                                </div>
                                <div class="form-group">
                                    <label>{!! trans('cms::redirect.code') !!}</label>
                                    <input type="text" class="form-control" id="code" name="code" placeholder="{!! trans('cms::redirect.code') !!}" value="{!! old('code') !!}">
                                    @include('cms::panel.inc.form_error',['input_name' => 'code'])
                                </div>
                                <div class="form-group">
                                    <label>{!! trans('cms::redirect.status') !!}</label>
                                    <div>
                                        <select class="custom-select custom-select-lg mb-3" name="status">
                                            <option value="1">{!! trans('cms::redirect.active') !!}</option>
                                            <option value="0">{!! trans('cms::redirect.passive') !!}</option>
                                        </select>
                                    </div>
                                    @include('cms::panel.inc.form_error',['input_name' => 'status'])
                                </div>
                                <div class="form-group page-date">
                                    <input type="submit" class="form-control btn-primary col-3" id="submit" value="{!! trans('cms::redirect.create') !!}">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

src/Resources/views/panel/redirect/edit.blade.php
@extends('cms::panel.inc.app')
@push('css')

@endpush

@push('js')
@endpush
@section('content')
    <div class="page-wrapper">
        <div class="container-fluid">
            @include('cms::panel.inc.breadcrumb')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-block">
                            <form method="POST" action="{!! route('redirects.update',['redirect' => $redirect]) !!}">
                                @method('PUT')
                                @csrf
                                <div class="form-group">
                                    <label>{!! trans('cms::redirect.from') !!}</label>
                                    <input type="text" class="form-control" id="from" name="from" placeholder="{!! trans('cms::redirect.from') !!}" value="{!! old('from') ?? $redirect->from !!}">
                                    @include('cms::panel.inc.form_error',['input_name' => 'from'])
                                </div>
                                <div class="form-group">
                                    <label>{!! trans('cms::redirect.to') !!}</label>
                                    <input type="text" class="form-control" id="to" name="to" placeholder="{!! trans('cms::redirect.to') !!}" value="{!! old('to') ?? $redirect->to !!}">
                                    @include('cms::panel.inc.form_error',['input_name' => 'to'])
                                </div>
                                <div class="form-group">
                                    <label>{!! trans('cms::redirect.code') !!}</label>
                                    <input type="text" class="form-control" id="code" name="code" placeholder="{!! trans('cms::redirect.code') !!}" value="{!! old('code') ?? $redirect->code !!}">
                                    @include('cms::panel.inc.form_error',['input_name' => 'code'])
                                </div>
                                <div class="form-group">
                                    <label>{!! trans('cms::redirect.status') !!}</label>
                                    <div>
                                        <select class="custom-select custom-select-lg mb-3" name="status">
                                            <option value="1" @if($redirect->status == 1) selected @endif>{!! trans('cms::redirect.active') !!}</option>
                                            <option value="0" @if($redirect->status == 0) selected @endif>{!! trans('cms::redirect.passive') !!}</option>
                                        </select>
                                    </div>
                                    @include('cms::panel.inc.form_error',['input_name' => 'status'])
                                </div>
                                <div class="form-group page-date">
                                    <input type="submit" class="form-control btn-primary col-3" id="submit" value="{!! trans('cms::redirect.edit') !!}">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

src/Resources/views/panel/redirect/index.blade.php
@extends('cms::panel.inc.app')
@push('css')

@endpush

@push('js')
<script>

    $(document).ready( function () {
        $('#tbl').DataTable();
    } );
    </script>
@endpush
@section('content')
    <div class="page-wrapper">
        <div class="container-fluid">
            @include('cms::panel.inc.breadcrumb')
            <div class="row">
                <div class="col-lg-12">
                    @include('cms::panel.inc.alert')
                    <div class="card">
                        <div class="card-block">
                            <h2 class="card-title">{!! trans('cms::redirect.redirects') !!}</h2>
                            @can('create',CMS\Models\Redirect::class)
                            <a class="btn-success btn float-right" href="{!! route('redirects.create') !!}">{!! trans('cms::redirect.create') !!}</a>
                            @endcan
                            <div class="table-responsive">
                                <table class="table" id="tbl">
                                    <thead>
                                    <tr>
                                        <th>{!! trans('cms::redirect.id') !!}</th>
                                        <th>{!! trans('cms::redirect.from') !!}</th>
                                        <th>{!! trans('cms::redirect.to') !!}</th>
                                        <th>{!! trans('cms::redirect.code') !!}</th>
                                        <th>{!! trans('cms::redirect.action') !!}</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($redirects as $redirect)
                                    <tr>
                                        <td>{!! $redirect->id !!}</td>
                                        <td>{!! $redirect->from !!}</td>
                                        <td>{!! $redirect->to !!}</td>
                                        <td>{!! $redirect->code !!}</td>
                                        <td>
                                            @can('update',$redirect)
                                            <a href="{!! route('redirects.edit' , ['redirect' => $redirect]) !!}" class="btn waves-effect waves-light btn-warning hidden-sm-down">{!! trans('cms::redirect.edit') !!}</a>
                                            @endcan
                                            @can('delete',$redirect)
                                                @include('cms::panel.inc.delete_modal', ['trans_file' => 'redirect', 'model' => $redirect, 'route_group' => 'redirects', 'route_parameter' => 'redirect'])
                                            @endcan
                                        </td>
                                    </tr>
                                    @endforeach
                                    </tbody>
                                </table>

{{--                                {{ $forms->links() }}--}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection