src/Routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::prefix('/panel')->middleware('auth')->group( function () {
    Route::resource('pages' , 'PageController');
    Route::get('pages/{id}/subpages','PageController@subPages')->name('subpages');
    Route::post('pages/checkurl','PageController@urlControl')->name('pages.checkurl');
    Route::resource('files' , 'FileController');
    Route::post('files/ajax','FileController@ajax')->name('file.ajax');
    Route::resource('languages' , 'LanguageController');
    Route::resource('categories','CategoryController');
    Route::post('category/order','CategoryController@order')->name('categories.order');

    Route::resource('metas' , 'MetaController');
    Route::resource('redirects' , 'RedirectController');

    //Form-Ebulletin
    Route::resource('forms','FormController');
    Route::resource('forms.messages','MessageController');
    Route::resource('messages','MessageController')->only(['show','store']);
    Route::resource('ebulletins' , 'EbulletinController');

    //Auth
    Route::resource('users' , 'UserController');
    Route::resource('roles' , 'RoleController');

    Route::get('/','HomeController@index')->name('panel');

    Route::get('login',function (){ return view('auth/login');})->name('login');

    Route::get('getFilePage','FileController@getFilePage')->name('files.getFilePage');
    Route::get('getFilePageDetail','FileController@getFilePageDetail')->name('files.getFilePageDetail');

    Route::post('saveFilePage','FileController@saveFilePage')->name('files.saveFilePage');
    Route::post('saveFilePageDetail','FileController@saveFilePageDetail')->name('files.saveFilePageDetail');

    Route::post('uploadFile','FileController@uploadFile')->name('files.uploadFile');

    Route::get('googleAnalytics','AnalyticsController@google')->name('analytics.google');

    Route::resource('slider','SliderController');
    Route::post('slider/add-image','SliderController@addImage')->name('addImage');
    Route::post('slider/delete-image','SliderController@deleteImage')->name('delimage');
    Route::post('slider/get-slider-image','SliderController@getSliderImage')->name('getSliderImage');
    Route::post('slider/edit-image','SliderController@editImage')->name('editImage');
    //Menu
    Route::resource('menu', 'MenuController');
    Route::post('menu/ajax','MenuController@ajax')->name('menuajax');
    Route::get('menu/item/{menuitem}/delete','MenuController@destroyMenuItem')->name('delete-item');
    Route::post('menuitem/ajax/','MenuController@storeMenuItem')->name('menuitemajax');

});

Route::get('panel/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('panel/login/', 'Auth\LoginController@login');
Route::post('panel/logout', 'Auth\LoginController@logout')->name('logout');


Route::group(['prefix'=>'ebulletin'],function(){
    Route::get('activate/{token}', 'EbulletinController@activate')->name('ebulletin-activate');
    Route::get('cancel/{token}', 'EbulletinController@cancel')->name('ebulletin-cancel');
    Route::post('store','EbulletinController@store')->name('ebulletin-store');
});


Route::post('form/store','MessageController@store')->name('form');
Route::fallback('UrlController@url');

Route::get('/home', 'HomeController@index')->name('home');
Route::any('/ckfinder/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')
    ->name('ckfinder_connector');

Route::any('/ckfinder/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')
    ->name('ckfinder_browser');

src/Models/Category.php
<?php

namespace CMS\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
	use Softdeletes;
    protected $fillable = ['parent_id','status'];

    public function detail()
    {
    	return $this->hasOne(CategoryDetail::class)->where('lang_id',default_lang());
    }

    public function details()
    {
        return $this->hasMany(CategoryDetail::class);
    }

    public function childrens()
    {
    	return $this->hasMany(Category::class,'parent_id')->orderBy('order');
    }

    public function pages()
    {
        return $this->belongsToMany(Page::class);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::deleting(function ($category){
            $category->details()->each(function ($detail)
            {
                $detail->delete();
            });
            $category->childrens()->each(function ($children)
            {
                $children->details()->each(function($detail){
                    $detail->delete();
                });
                $children->delete();
            });
        });
    }
}

src/Resources/views/panel/category/create.blade.php
@extends('cms::panel.inc.app')
@push('css')
    <style>
        .ck-editor__editable_inline {
            min-height: 400px;
        }
    </style>
@endpush

@push('js')
    <script type="text/javascript">
        $('.custom-select').change(function(){
            var parent_id = $(this).val();
            $.ajax({
                url:'{!! route('categories.order') !!}',
                method:'POST',
                data:{"_token": "{{ csrf_token() }}",parent_id},
                success:function(data){
                    $('#order').html("");
                    if (data.orders.length < 1) {
                        $('#order').append('<option value="1">"1"</option>');
                    }
                    $.each(data.orders, function(key,value){
                        $('#order').append('<option value='+value+'>'+value+'</option>');
                    });
                }
            });
        });
    </script>
@endpush
@section('content')
    <div class="page-wrapper">
        <div class="container-fluid">
            @include('cms::panel.inc.breadcrumb')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-block">
                            <form method="POST" action="{!! route('categories.store') !!}" enctype="multipart/form-data">
                                @method('POST')
                                @csrf
                                <div class="form-group page-status col-lg-2 float-left ml-4">
                                    <label>{!! trans('cms::panel.type') !!}</label>
                                    <div>
                                        <select class="custom-select custom-select-lg mb-3" name="parent_id">
                                            <option value="0">Parent</option>
                                            @foreach($categories as $category)
                                                <option value="{!! $category->id !!}">{!! $category->name !!}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col-2 float-left ml-4">
                                    <label>{!! trans('cms::panel.order') !!}</label>
                                    <div>
                                            <select class="custom-select custom-select-lg mb-3 order" id="order" name="order">
                                                    <option value="{!! $order !!}">{!! $order !!}</option>
                                            </select>
                                    </div>
                                </div>
                                <div class="form-group col-4 float-left ml-4">
                                    <label>Category Picture</label>
                                    <input type="file" class="form-control" name="picture"/>
                                </div>
                                <div class="form-group page-status col-lg-2 float-left ml-4">
                                    <label>{!! trans('cms::panel.status') !!}</label>
                                    <div>
                                        <input type="radio" id="ac" value="1" class="form-control" name="status" > <label for="ac">{!! trans('cms::panel.active') !!}</label>
                                    </div>
                                    <div>
                                        <input type="radio" value="0" id="ps" class="form-control" name="status" checked> <label for="ps">{!! trans('cms::panel.passive') !!}</label>
                                    </div>
                                </div>
                        </div>
                            </div>
                                <div class="form-group page-language">
                                    @foreach( app()->activeLanguages as $l)
                                        <div class="card">
                                            <div class="card-block">
                                                <div class="form-group">
                                                    <input type="checkbox" id="{!! $l->id  !!}" value="1" class="form-control-user" name="detail_status[{!! $l->id !!}]" checked /> <label for="{!! $l->id !!}">{!! $l->name !!}</label>
                                                </div>
                                                <div id="lang{!! $l !!}" >
                                                    <div class="form-group">
                                                        <label>{!! trans('cms::category.name') !!}</label>
                                                        <input type="text" class="form-control page-name"  name="name[{!! $l->id !!}]" placeholder="{!!trans('cms::category.name') !!}" required />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                                <div class="form-group page-date">
                                    <input type="submit" class="btn btn-success float-right" id="submit" value="{!! trans('cms::panel.create') !!}">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

src/Resources/views/panel/category/edit.blade.php
@extends('cms::panel.inc.app')
@push('css')
    <style>
        .ck-editor__editable_inline {
            min-height: 400px;
        }
    </style>
@endpush

@push('js')
@endpush
@section('content')
    <div class="page-wrapper">
        <div class="container-fluid">
            @include('cms::panel.inc.breadcrumb')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-block">
                            <form method="POST" action="{!! route('categories.store') !!}" enctype="multipart/form-data">
                                @method('POST')
                                @csrf
                                <div class="form-group page-status col-lg-2 float-left ml-4">
                                    <label>{!! trans('cms::panel.type') !!}</label>
                                    <div>
                                        <select class="custom-select custom-select-lg mb-3" name="parent_id">
                                            <option value="0">Parent</option>
                                            @foreach($categories as $category)
                                                <option value="{!! $category->id !!}">{!! $category->name !!}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col-2 float-left ml-4">
                                            <label>{!! trans('cms::panel.order') !!}</label>
                                            <input type="number" id="ac" class="form-control" name="order" value="{!! $page->order !!}"/>
                                </div>
                                <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                <div class="form-group col-4 float-left ml-4">
                                    <label>Category Picture</label>
                                    <input type="file" class="form-control" name="picture"/>
                                    <button type="button" class="btn btn-primary col-12 mt-1" data-toggle="modal" data-target="#exampleModalCenter">
                                        Choose File
                                    </button>
                                </div>
                                <div class="form-group page-status col-lg-2 float-left ml-4">
                                    <label>{!! trans('cms::panel.status') !!}</label>
                                    <div>
                                        <input type="radio" id="ac" value="1" class="form-control" name="status" > <label for="ac">{!! trans('cms::panel.active') !!}</label>
                                    </div>
                                    <div>
                                        <input type="radio" value="0" id="ps" class="form-control" name="status" checked> <label for="ps">{!! trans('cms::panel.passive') !!}</label>
                                    </div>
                                </div>
                        </div>
                            </div>
                                <div class="form-group page-language">
                                    @foreach( app()->activeLanguages as $l)
                                        <div class="card">
                                            <div class="card-block">
                                                <div class="form-group">
                                                    <input type="checkbox" id="{!! $l->id  !!}" value="1" class="form-control-user" name="detail_status[{!! $l->id !!}]" checked /> <label for="{!! $l->id !!}">{!! $l->name !!}</label>
                                                </div>
                                                <div id="lang{!! $l !!}" >
                                                    <div class="form-group">
                                                        <label>{!! trans('cms::category.name') !!}</label>
                                                        <input type="text" class="form-control page-name"  name="name[{!! $l->id !!}]" placeholder="{!!trans('cms::category.name') !!}"/>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                                <div class="form-group page-date">
                                    <input type="submit" class="btn btn-success float-right" id="submit" value="{!! trans('cms::panel.edit') !!}">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal" tabindex="-1" id="exampleModalCenter" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Sunucudaki Resimler</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @if(isset($files))
                    @foreach($files as $file)
                        <div class="form-group float-left">
                            <input type="radio" class="ajax_image" id="{!! $file->id !!}" name="file_id" value="{!! $file->id !!}">
                            <label  for="{!! $file->id !!}"></label>
                            <img src="{!! asset("/storage/".$file->path) !!}" style="width: 50px;height:50px;"/>
                        </div>
                    @endforeach
                @endif
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary ajax_post">Save changes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
@endsection

src/Resources/views/panel/category/index.blade.php
@extends('cms::panel.inc.app')
@push('css')

@endpush

@push('js')

@endpush
@php($margin = 20)
@section('content')
    <div class="page-wrapper">
        <div class="container-fluid">
            @include('cms::panel.inc.breadcrumb')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-block">
                            <h4 class="card-title">{!! trans('cms::panel.categories') !!}</h4>
                            <a class="btn-success btn float-right" href="{!! route('categories.create') !!}">{!! trans('cms::panel.create') !!}</a>
                            <div class="table-responsive"></div>
                            <ul class="list-group">
                             @foreach($categories as $category)
                                 <li class="list-group-item mt-2  justify-content-between bg-light">{!! $category->name  !!}
                                     <div class="btn-group" role="group" aria-label="Basic example">
                                          <a href="{!! route('categories.edit',['category' => $category->id ]) !!}" type="button" class="btn-success btn">{!! trans('cms::panel.edit') !!}</a>
                                          @include('cms::panel.inc.delete_modal',['trans_file' => 'category', 'model' => $category, 'route_group' => 'categories', 'route_parameter' => 'category'])
                                    </div>
                                </li>
                                 @if(count($category->childrens))
                                    @include('cms::panel.category.treeView',['childs' => $category->childrens,'margin' => $margin])
                                 @endif
                             @endforeach
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

src/Resources/views/panel/category/treeView.blade.php
@foreach($childs as $child)
    <li class="list-group-item mt-2  justify-content-between" style="margin-left:{!! $margin !!}px;">{!! $child->detail->name !!}
         <div class="btn-group" role="group" aria-label="Basic example">
              <a href="{!! route('categories.edit',['category' => $child->id ]) !!}" type="button" class="btn-success btn">{!! trans('cms::panel.edit') !!}</a>
             @include('cms::panel.inc.delete_modal',['trans_file' => 'category', 'model' => $category, 'route_group' => 'categories', 'route_parameter' => 'category'])
        </div>
    </li>
    @if(count($child->childrens))
		@include('cms::panel.category.treeView',['childs' => $child->childrens , 'margin' => $margin + 20])
    @endif
@endforeach