src/Routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::prefix('/panel')->middleware('auth')->group( function () {
    Route::resource('pages' , 'PageController');
    Route::get('pages/{id}/subpages','PageController@subPages')->name('subpages');
    Route::post('pages/checkurl','PageController@urlControl')->name('pages.checkurl');
    Route::resource('files' , 'FileController');
    Route::post('files/ajax','FileController@ajax')->name('file.ajax');
    Route::resource('languages' , 'LanguageController');
    Route::resource('categories','CategoryController');
    Route::post('category/order','CategoryController@order')->name('categories.order');

    Route::resource('metas' , 'MetaController');
    Route::resource('redirects' , 'RedirectController');

    //Form-Ebulletin
    Route::resource('forms','FormController');
    Route::resource('forms.messages','MessageController');
    Route::resource('messages','MessageController')->only(['show','store']);
    Route::resource('ebulletins' , 'EbulletinController');

    //Auth
    Route::resource('users' , 'UserController');
    Route::resource('roles' , 'RoleController');

    Route::get('/','HomeController@index')->name('panel');

    Route::get('login',function (){ return view('auth/login');})->name('login');

    Route::get('getFilePage','FileController@getFilePage')->name('files.getFilePage');
    Route::get('getFilePageDetail','FileController@getFilePageDetail')->name('files.getFilePageDetail');

    Route::post('saveFilePage','FileController@saveFilePage')->name('files.saveFilePage');
    Route::post('saveFilePageDetail','FileController@saveFilePageDetail')->name('files.saveFilePageDetail');

    Route::post('uploadFile','FileController@uploadFile')->name('files.uploadFile');

    Route::get('googleAnalytics','AnalyticsController@google')->name('analytics.google');

    Route::resource('slider','SliderController');
    Route::post('slider/add-image','SliderController@addImage')->name('addImage');
    Route::post('slider/delete-image','SliderController@deleteImage')->name('delimage');
    Route::post('slider/get-slider-image','SliderController@getSliderImage')->name('getSliderImage');
    Route::post('slider/edit-image','SliderController@editImage')->name('editImage');
    //Menu
    Route::resource('menu', 'MenuController');
    Route::post('menu/ajax','MenuController@ajax')->name('menuajax');
    Route::get('menu/item/{menuitem}/delete','MenuController@destroyMenuItem')->name('delete-item');
    Route::post('menuitem/ajax/','MenuController@storeMenuItem')->name('menuitemajax');

});

Route::get('panel/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('panel/login/', 'Auth\LoginController@login');
Route::post('panel/logout', 'Auth\LoginController@logout')->name('logout');


Route::group(['prefix'=>'ebulletin'],function(){
    Route::get('activate/{token}', 'EbulletinController@activate')->name('ebulletin-activate');
    Route::get('cancel/{token}', 'EbulletinController@cancel')->name('ebulletin-cancel');
    Route::post('store','EbulletinController@store')->name('ebulletin-store');
});


Route::post('form/store','MessageController@store')->name('form');
Route::fallback('UrlController@url');

Route::get('/home', 'HomeController@index')->name('home');
Route::any('/ckfinder/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')
    ->name('ckfinder_connector');

Route::any('/ckfinder/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')
    ->name('ckfinder_browser');

src/Models/Role.php
<?php

namespace CMS\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Role extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'name',
    ];

    public function users(){
        return $this->belongsTo('CMS\User');
    }

    public function permissions(){
        return $this->hasMany('CMS\Permission');
    }

    public function hasModulePermission($module_id,$permission){
        $check = ModulePermission::where('role_id',$this->id)
            ->where('module_id',$module_id)
            ->where('permission',$permission)
            ->first();
        return ($check ? true : false);
    }

    public function hasPagePermission($page_id,$permission){
        $check = PagePermission::where('role_id',$this->id)
            ->where('page_id',$page_id)
            ->where('permission',$permission)
            ->first();
        return ($check ? true : false);
    }
}

src/Resources/views/panel/role/create.blade.php
@extends('cms::panel.inc.app')
@push('css')

@endpush

@push('js')
@endpush
@section('content')
    <div class="page-wrapper">
        <div class="container-fluid">
@include('cms::panel.inc.breadcrumb')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-block">
                            <form method="POST" action="{!! route('roles.store') !!}">
                                @method('POST')

                                @csrf

                                <div class="form-group">
                                    <label>{!! trans('cms::role.name') !!}</label>
                                    <input type="text" class="form-control" id="name" name="name" placeholder="{!! trans('cms::role.name') !!}" value="{!! old('name') !!}">
{{--                        --}}@include('cms::panel.inc.form_error',['input_name' => 'name'])
                                </div>
                                <div>
                                    <h2>{!! trans('cms::role.module_permissions') !!}</h2>
{{--                            --}}@foreach($modules as $module)
                                    <div class="form-group">
                                        <label><strong>{!! trans('cms::role.module_'.$module->name) !!}</strong></label>
                                        <div>
                                            <input type="checkbox" class="form-control" id="module[{!! $module->id !!}]_create" name="module[{!! $module->id !!}][]" value="C" {{ is_array(old('module.'.$module->id)) && in_array('C',old('module.'.$module->id)) ? 'checked' : '' }}>
                                            <label for="module[{!! $module->id !!}]_create">{!! trans('cms::role.create') !!}</label>
                                            <input type="checkbox" class="form-control" id="module[{!! $module->id !!}]_read" name="module[{!! $module->id !!}][]" value="R" {{ is_array(old('module.'.$module->id)) && in_array('R',old('module.'.$module->id)) ? 'checked' : '' }}>
                                            <label for="module[{!! $module->id !!}]_read">{!! trans('cms::role.read') !!}</label>
                                            <input type="checkbox" class="form-control" id="module[{!! $module->id !!}]_update" name="module[{!! $module->id !!}][]" value="U" {{ is_array(old('module.'.$module->id)) && in_array('U',old('module.'.$module->id)) ? 'checked' : '' }}>
                                            <label for="module[{!! $module->id !!}]_update">{!! trans('cms::role.update') !!}</label>
                                            <input type="checkbox" class="form-control" id="module[{!! $module->id !!}]_delete" name="module[{!! $module->id !!}][]" value="D" {{ is_array(old('module.'.$module->id)) && in_array('D',old('module.'.$module->id)) ? 'checked' : '' }}>
                                            <label for="module[{!! $module->id !!}]_delete">{!! trans('cms::role.delete') !!}</label>
                                        </div>
                                    </div>
{{--                            --}}@endforeach
                                </div>
                                <hr>
                                <div>
                                    <h2>{!! trans('cms::role.page_permissions') !!}</h2>
{{--                                --}}@foreach($pages as $page)
                                    <div class="form-group">
                                        <label>{!! $page->name !!}</label>
                                        <div>
                                            <input type="checkbox" class="form-control" id="page[{!! $page->id !!}]_create" name="page[{!! $page->id !!}][]" value="C">
                                            <label for="page[{!! $page->id !!}]_create">{!! trans('cms::role.create') !!}</label>
                                            <input type="checkbox" class="form-control" id="page[{!! $page->id !!}]_read" name="page[{!! $page->id !!}][]" value="R">
                                            <label for="page[{!! $page->id !!}]_read">{!! trans('cms::role.read') !!}</label>
                                            <input type="checkbox" class="form-control" id="page[{!! $page->id !!}]_update" name="page[{!! $page->id !!}][]" value="U">
                                            <label for="page[{!! $page->id !!}]_update">{!! trans('cms::role.update') !!}</label>
                                            <input type="checkbox" class="form-control" id="page[{!! $page->id !!}]_delete" name="page[{!! $page->id !!}][]" value="D">
                                            <label for="page[{!! $page->id !!}]_delete">{!! trans('cms::role.delete') !!}</label>
                                        </div>
                                    </div>
{{--                                --}}@endforeach
                                </div>
                                <div class="form-group page-date">
                                    <input type="submit" class="form-control btn-primary col-3" id="submit" value="{!! trans('cms::role.create') !!}">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

src/Resources/views/panel/role/edit.blade.php
@extends('cms::panel.inc.app')
@push('css')

@endpush

@push('js')
@endpush
@section('content')
    <div class="page-wrapper">
        <div class="container-fluid">
            @include('cms::panel.inc.breadcrumb')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-block">
                            <form method="POST" action="{!! route('roles.update',array('role'=>$role)) !!}">
                                @method('PUT')

                                @csrf

                                <div class="form-group">
                                    <label>{!! trans('cms::role.name') !!}</label>
                                    <input type="text" class="form-control" id="name" name="name" placeholder="{!! trans('cms::role.name') !!}" value="{!! $role->name !!}">
{{--                        --}}@include('cms::panel.inc.form_error',['input_name' => 'name'])
                                </div>
                                <div>
                                    <h2>{!! trans('cms::role.module_permissions') !!}</h2>
{{--                            --}}@foreach($modules as $module)
                                        <div class="form-group">
                                            <label><strong>{!! trans('cms::role.module_'.$module->name) !!}</strong></label>
                                            <div>
                                                <input type="checkbox" class="form-control" id="module[{!! $module->id !!}]_create" name="module[{!! $module->id !!}][]" value="C" {{ $role->hasModulePermission($module->id,'C') ? 'checked' : '' }}>
                                                <label for="module[{!! $module->id !!}]_create">{!! trans('cms::role.create') !!}</label>
                                                <input type="checkbox" class="form-control" id="module[{!! $module->id !!}]_read" name="module[{!! $module->id !!}][]" value="R" {{ $role->hasModulePermission($module->id,'R') ? 'checked' : '' }}>
                                                <label for="module[{!! $module->id !!}]_read">{!! trans('cms::role.read') !!}</label>
                                                <input type="checkbox" class="form-control" id="module[{!! $module->id !!}]_update" name="module[{!! $module->id !!}][]" value="U" {{ $role->hasModulePermission($module->id,'U') ? 'checked' : '' }}>
                                                <label for="module[{!! $module->id !!}]_update">{!! trans('cms::role.update') !!}</label>
                                                <input type="checkbox" class="form-control" id="module[{!! $module->id !!}]_delete" name="module[{!! $module->id !!}][]" value="D" {{ $role->hasModulePermission($module->id,'D') ? 'checked' : '' }}>
                                                <label for="module[{!! $module->id !!}]_delete">{!! trans('cms::role.delete') !!}</label>
                                            </div>
                                        </div>
{{--                            --}}@endforeach
                                </div>
                                <hr>
                                <div>
                                    <h2>{!! trans('cms::role.page_permissions') !!}</h2>
{{--                                --}}@foreach($pages as $page)
                                        <div class="form-group">
                                            <label>{!! $page->name !!}</label>
                                            <div>
                                                <input type="checkbox" class="form-control" id="page[{!! $page->id !!}]_create" name="page[{!! $page->id !!}][]" value="C" {{ $role->hasPagePermission($page->id,'C') ? 'checked' : '' }}>
                                                <label for="page[{!! $page->id !!}]_create">{!! trans('cms::role.create') !!}</label>
                                                <input type="checkbox" class="form-control" id="page[{!! $page->id !!}]_read" name="page[{!! $page->id !!}][]" value="R" {{ $role->hasPagePermission($page->id,'R') ? 'checked' : '' }}>
                                                <label for="page[{!! $page->id !!}]_read">{!! trans('cms::role.read') !!}</label>
                                                <input type="checkbox" class="form-control" id="page[{!! $page->id !!}]_update" name="page[{!! $page->id !!}][]" value="U" {{ $role->hasPagePermission($page->id,'U') ? 'checked' : '' }}>
                                                <label for="page[{!! $page->id !!}]_update">{!! trans('cms::role.update') !!}</label>
                                                <input type="checkbox" class="form-control" id="page[{!! $page->id !!}]_delete" name="page[{!! $page->id !!}][]" value="D" {{ $role->hasPagePermission($page->id,'D') ? 'checked' : '' }}>
                                                <label for="page[{!! $page->id !!}]_delete">{!! trans('cms::role.delete') !!}</label>
                                            </div>
                                        </div>
{{--                                --}}@endforeach
                                </div>
                                <div class="form-group page-date">
                                    <input type="submit" class="form-control btn-primary col-3" id="submit" value="{!! trans('cms::role.edit') !!}">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

src/Resources/views/panel/role/index.blade.php
@extends('cms::panel.inc.app')
@push('css')

@endpush

@push('js')
<script>

    $(document).ready( function () {
        $('#tbl').DataTable();
    } );
    </script>
@endpush
@section('content')
    <div class="page-wrapper">
        <div class="container-fluid">
            @include('cms::panel.inc.breadcrumb')
            <div class="row">
                <div class="col-lg-12">
                    @include('cms::panel.inc.alert')
                    <div class="card">
                        <div class="card-block">
                            <h4 class="card-title">{!! trans('cms::role.roles') !!}</h4>
                            <a class="btn-success btn float-right" href="{!! route('roles.create') !!}">{!! trans('cms::role.create') !!}</a>
                            <div class="table-responsive">
                                <table class="table" id="table">
                                    <thead>
                                    <tr>
                                        <th>{!! trans('cms::role.id') !!}</th>
                                        <th>{!! trans('cms::role.name') !!}</th>
                                        <th>{!! trans('cms::role.action') !!}</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($roles as $role)
                                    <tr>
                                        <td>{!! $role->id !!}</td>
                                        <td>{!! $role->name !!}</td>
                                        <td>
                                            <a href="{!! route('roles.edit' , ['role' => $role]) !!}" class="btn waves-effect waves-light btn-warning hidden-sm-down">{!! trans('cms::role.edit') !!}</a>
                                            @include('cms::panel.inc.delete_modal',['trans_file' => 'role', 'model' => $role, 'route_group' => 'roles', 'route_parameter' => 'role'])
                                        </td>
                                    </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection